In [6]:
import numpy as np

def conv2d_with_padding(image, kernel, padding=0):
    image_height, image_width = image.shape
    kernel_height, kernel_width = kernel.shape
    
    # Apply padding to the input image
    padded_image = np.pad(image, 
                          ((padding, padding), (padding, padding)), 
                          mode='constant', 
                          constant_values=0)
    
    padded_height, padded_width = padded_image.shape
    
    # Calculate dimensions of the output array
    output_height = padded_height - kernel_height + 1
    output_width = padded_width - kernel_width + 1

    # Initialize the output array and regions list
    output = np.zeros((output_height, output_width))
    regions = []
    
    # Perform convolution
    for i in range(output_height):
        for j in range(output_width):
            region = padded_image[i:i + kernel_height, j:j + kernel_width]
            regions.append(region)
            output[i, j] = np.sum(region * kernel)
    
    return output, regions

# Example usage
image = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

kernel = np.array([[1, 0],
                   [0, -1]])

padding = 1
output, regions = conv2d_with_padding(image, kernel, padding)

print("Output:")
print(output)

print("Regions:")
for num, region in enumerate(regions, 1):
    print("\n")
    print(f"Region {num}:")
    print(region)


Output:
[[ -1.  -2.  -3.  -4.   0.]
 [ -5.  -5.  -5.  -5.   4.]
 [ -9.  -5.  -5.  -5.   8.]
 [-13.  -5.  -5.  -5.  12.]
 [  0.  13.  14.  15.  16.]]
Regions:


Region 1:
[[0 0]
 [0 1]]


Region 2:
[[0 0]
 [1 2]]


Region 3:
[[0 0]
 [2 3]]


Region 4:
[[0 0]
 [3 4]]


Region 5:
[[0 0]
 [4 0]]


Region 6:
[[0 1]
 [0 5]]


Region 7:
[[1 2]
 [5 6]]


Region 8:
[[2 3]
 [6 7]]


Region 9:
[[3 4]
 [7 8]]


Region 10:
[[4 0]
 [8 0]]


Region 11:
[[0 5]
 [0 9]]


Region 12:
[[ 5  6]
 [ 9 10]]


Region 13:
[[ 6  7]
 [10 11]]


Region 14:
[[ 7  8]
 [11 12]]


Region 15:
[[ 8  0]
 [12  0]]


Region 16:
[[ 0  9]
 [ 0 13]]


Region 17:
[[ 9 10]
 [13 14]]


Region 18:
[[10 11]
 [14 15]]


Region 19:
[[11 12]
 [15 16]]


Region 20:
[[12  0]
 [16  0]]


Region 21:
[[ 0 13]
 [ 0  0]]


Region 22:
[[13 14]
 [ 0  0]]


Region 23:
[[14 15]
 [ 0  0]]


Region 24:
[[15 16]
 [ 0  0]]


Region 25:
[[16  0]
 [ 0  0]]
