In [16]:
import numpy as np

def conv2d(image,kernel):
    image_height,image_width=image.shape
    kernel_height,kernel_width=kernel.shape

    output_height=image_height-kernel_height+1
    output_width=image_width-kernel_width+1
    
    output=np.zeros((output_height,output_width))
    region=[]
    regions_collected=[]

    for i in range(output_height):
        for j in range(output_width):
            region=image[i:i+kernel_height,j:j+kernel_width]
            regions_collected.append(region)
            output[i,j]=np.sum(region*kernel)

        return output,regions_collected
    
image=np.array([[2,3,4,5,6],[4,78,12,14,1],[2,1,10,11,14],[12,13,11,12,1],[21,32,41,5,6]])
kernel=np.array([[2,3],[3,4]])
    
output_image,regions_col=conv2d(image=image,
                    kernel=kernel)

print(f' Output Image -----> \n{output_image} ')
print("\n")

print(f' Actual Image-----> \n{image} ')
print("\n")


print("Regions rolled over: ----->")
for num,reg in enumerate(regions_col,1):
    print(f'Region number {num}\n {reg}')

 Output Image -----> 
[[337. 300. 115.  74.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]] 


 Actual Image-----> 
[[ 2  3  4  5  6]
 [ 4 78 12 14  1]
 [ 2  1 10 11 14]
 [12 13 11 12  1]
 [21 32 41  5  6]] 


Regions rolled over: ----->
Region number 1
 [[ 2  3]
 [ 4 78]]
Region number 2
 [[ 3  4]
 [78 12]]
Region number 3
 [[ 4  5]
 [12 14]]
Region number 4
 [[ 5  6]
 [14  1]]


array([[2, 3],
       [3, 4]])